// // "use client";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
// import React from "react";

import Navbar from "@/components/navbar/Navbar";
import styles from "./layout.module.css";
// import Footer from "@/components/footer/Footer";

// // import page from "./page";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <>
//       <div style={{ backgroundColor: "black" }}>
//         <Navbar />
//         <div
//           className={styles.container}
//           // style={{
//           //   backgroundColor: "#0D111C",
//           //   width: "99vw",
//           //   justifyContent: "center",

//           //   display: "flex",
//           // }}
//         >
//           {children}
//         </div>
//       </div>
//     </>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

// const hydratedFooter = dynamic(() => import("@/components/footer/Footer"));

// import Footer from "@/components/footer/Footer";

// import Footer from "@/components/footer/Footer";

// import ClientSideProviderTest from "@/components/clientSideProviderTest";

const inter = Inter({ subsets: ["latin"] });
const Footer = dynamic(() => import("@/components/footer/footer"));
export const metadata = {
  title: {
    default: "Next.js 14 Homepage",
    template: "%s | Next.js 14",
  },
  description: "Next.js starter app description",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ClientSideProviderTest> */}
        <div className={styles.container}>
          <Navbar />
          {children}
          <Footer />
        </div>
        {/* </ClientSideProviderTest> */}
      </body>
    </html>
  );
}
